/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.*;
import java.util.Calendar;
import java.util.List;

public class frmAdministrador extends javax.swing.JFrame {
    
    Lista listaProductos;
    
    public frmAdministrador( Lista lista ){
        
        initComponents();
        setLocationRelativeTo( null );
        Calendar fechaHora = Calendar.getInstance();
        lblBienvenida.setText( lblBienvenida.getText() + "  Administrador  " + Usuarios.usuarioActual.getNombreUsuario() );
        lblFechaHora.setText( String.format( "%tr, %1$TA, %1$TB %1$Td, %1$TY", fechaHora, fechaHora ) );
        listaProductos = lista;
        
    }
    
    public frmAdministrador() {
        initComponents();
        setLocationRelativeTo( null );
        Calendar fechaHora = Calendar.getInstance();
        lblBienvenida.setText( lblBienvenida.getText() + "  Administrador  " + Usuarios.usuarioActual.getNombreUsuario() );
        lblFechaHora.setText( String.format( "%tr, %1$TA, %1$TB %1$Td, %1$TY", fechaHora, fechaHora ) );
        Almacen.inicializarLista();
        listaProductos = Almacen.listaProductos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenida = new javax.swing.JLabel();
        btnVerAdministradores = new javax.swing.JButton();
        btnVerClientes = new javax.swing.JButton();
        btnVerAlmacen = new javax.swing.JButton();
        btnVerVentas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFechaHora = new javax.swing.JLabel();
        btnMenuPrincipal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setText("Bienvenida (o) :");

        btnVerAdministradores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerAdministradores.setText("Ver Administradores");
        btnVerAdministradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAdministradoresActionPerformed(evt);
            }
        });

        btnVerClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerClientes.setText("Ver clientes");
        btnVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClientesActionPerformed(evt);
            }
        });

        btnVerAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerAlmacen.setText("Ver almacen");
        btnVerAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlmacenActionPerformed(evt);
            }
        });

        btnVerVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerVentas.setText("Ver todas las ventas");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/225e80aa4d92f993b7f82e9ba19fd0e0.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblFechaHora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMenuPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerAlmacen)
                            .addComponent(btnVerVentas)
                            .addComponent(btnVerClientes)
                            .addComponent(btnVerAdministradores))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnMenuPrincipal)
                .addGap(28, 28, 28)
                .addComponent(lblBienvenida)
                .addGap(34, 34, 34)
                .addComponent(lblFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVerAlmacen)
                        .addGap(76, 76, 76)
                        .addComponent(btnVerAdministradores)
                        .addGap(65, 65, 65)
                        .addComponent(btnVerClientes)
                        .addGap(75, 75, 75)
                        .addComponent(btnVerVentas))
                    .addComponent(jLabel1))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerClientesActionPerformed

    private void btnVerAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlmacenActionPerformed
        // TODO add your handling code here:
        frmAlmacen a = new frmAlmacen( listaProductos );
        a.setVisible( true );
        this.dispose();
    }//GEN-LAST:event_btnVerAlmacenActionPerformed

    private void btnVerAdministradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAdministradoresActionPerformed
        // TODO add your handling code here:
        frmAdministradores a = new frmAdministradores();
        a.setVisible( true );
        this.dispose();
    }//GEN-LAST:event_btnVerAdministradoresActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        // TODO add your handling code here:
        Login a = new Login();
        a.setVisible( true );
        this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnVerAdministradores;
    private javax.swing.JButton btnVerAlmacen;
    private javax.swing.JButton btnVerClientes;
    private javax.swing.JButton btnVerVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblFechaHora;
    // End of variables declaration//GEN-END:variables
}
